name: Build and Prepare Package

on:
  push:
    branches:
      - release

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # o la versión que uses

      - name: Install dependencies
        run: yarn install

      - name: Build package
        run: yarn build:app

      - name: Create package.json for distribution
        run: |
          node -e "const pkg = require('./package.json'); delete pkg.devDependencies; delete pkg.scripts; require('fs').writeFileSync('dist/package.json', JSON.stringify(pkg, null, 2));"

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -m "Automated build" && git push)
